# docker-compose.yml
version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: my_fridge_db
    environment:
      POSTGRES_USER: jmgjmg102
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fridge_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: my_fridge_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: